### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by jacobludriks** [christkv/kerberos#16]
When running the example code in the test folder, I get the following:

```
c:\scripts\winrmjs\index.js:339
krb.authGSSClientInit('username@domain.com',Kerberos.GSS_C_MUTUAL_FLAG, f
    ^
TypeError: undefined is not a function
    at Object.<anonymous> (c:\scripts\winrmjs\index.js:339:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

```

**Comment by christkv** [comment]
test examples do not work and unfortunately there is no straightforward way of testing kerberos without a full kerberos installation.
