### ISSUE TITLE
Test fails on Unix with undefined symbol: GSS_C_NT_HOSTBASED_SERVICE

### ISSUE THREAD

**Issue by huaraz** [christkv/kerberos#19]
Sorry I am new to node/npm/jspm, .. and need some kerberos/gss functionality.  I installed this package, but when I try to run the test I get: 

...../node_modules/kerberos/build/Release/kerberos.node: undefined symbol: GSS_C_NT_HOSTBASED_SERVICE
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/markus/sources/github-master/node_modules/kerberos/lib/kerberos.js:1:78)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by christkv** [comment]
this module is specifically made for mongodb kerberos support. no tests will work when not having the correct environment. kerberos testing is non-trivial unfortunately so it's a manual affair for now.
