### ISSUE TITLE
Errors during installation version 0.0.14

### ISSUE THREAD

**Issue by andriichyzh** [christkv/kerberos#27]
On installing `mongodb` driver I got errors from `kerberos` module.
OS: Ubuntu 14.04 x64

#### Node 0.12.7
```bash
user@host:test$ npm i kerberos

> kerberos@0.0.14 install /home/user/test/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory `/home/user/test/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
  CXX(target) Release/obj.target/kerberos/lib/worker.o
  CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
../lib/kerberosgss.c:27:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic push
 ^
../lib/kerberosgss.c:28:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic ignored "-Wdeprecated-declarations"
 ^
../lib/kerberosgss.c: In function ‘authenticate_gss_client_wrap’:
../lib/kerberosgss.c:348:19: warning: variable ‘server_conf_flags’ set but not used [-Wunused-but-set-variable]
   char buf[4096], server_conf_flags;
                   ^
../lib/kerberosgss.c: At top level:
../lib/kerberosgss.c:687:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic pop
 ^
  CC(target) Release/obj.target/kerberos/lib/base64.o
  CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
  SOLINK_MODULE(target) Release/obj.target/kerberos.node
/usr/bin/ld: cannot find -lkrb5
/usr/bin/ld: cannot find -lgssapi_krb5
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/kerberos.node] Error 1
make: Leaving directory `/home/user/test/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.13.0-63-generic
gyp ERR! command "node" "/home/user/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/test/node_modules/kerberos
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
kerberos@0.0.14 node_modules/kerberos
└── nan@2.0.9
```

#### Node 4.0.0
```bash
user@host:test$ npm i kerberos

> kerberos@0.0.14 install /home/user/test/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory `/home/user/test/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
  CXX(target) Release/obj.target/kerberos/lib/worker.o
  CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
../lib/kerberosgss.c:27:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic push
 ^
../lib/kerberosgss.c:28:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic ignored "-Wdeprecated-declarations"
 ^
../lib/kerberosgss.c: In function ‘authenticate_gss_client_wrap’:
../lib/kerberosgss.c:348:19: warning: variable ‘server_conf_flags’ set but not used [-Wunused-but-set-variable]
   char buf[4096], server_conf_flags;
                   ^
../lib/kerberosgss.c: At top level:
../lib/kerberosgss.c:687:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic pop
 ^
  CC(target) Release/obj.target/kerberos/lib/base64.o
  CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
  SOLINK_MODULE(target) Release/obj.target/kerberos.node
/usr/bin/ld: cannot find -lkrb5
/usr/bin/ld: cannot find -lgssapi_krb5
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/kerberos.node] Error 1
make: Leaving directory `/home/user/test/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-63-generic
gyp ERR! command "/home/user/.nvm/versions/node/v4.0.0/bin/node" "/home/user/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/test/node_modules/kerberos
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
kerberos@0.0.14 node_modules/kerberos
└── nan@2.0.9
```

**Comment by christkv** [comment]
install the MIT kerberos library.

**Comment by andriichyzh** [comment]
Thanks!
After installing `libkrb5-dev` it was fixed. 

Is this required library for `npm i mongodb` (from `kerberos@0.0.14`)?

**Comment by christkv** [comment]
only for kerberos support. the error will not stop the driver from working as the dependency is optional but people get confused by the error print out.

**Comment by andriichyzh** [comment]
Thanks for clarification!
This is good news that it is not a critical error :)

**Comment by wyvernnot** [comment]
The error is muted after installing `libkrb5-dev`, clarification really helpful :beers:

**Comment by devKC** [comment]
Hello, I know it has been some time and this thread is closed, but I was wondering how to install MIT kerberos library on my mac. Is there a npm command or do I download something over the web (if so which link)? Thank you!
