### ISSUE TITLE
npm install as dependency fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by StephanBijzitter** [christkv/kerberos#42]
Installing with `--unsafe-perm` is to no avail.

Except from npm-debug:
```
40945 silly install kerberos@0.0.18 /vagrant/node_modules/.staging/kerberos-9299cbb858935cda4e8d3dc405e57d65
40946 info lifecycle kerberos@0.0.18~install: kerberos@0.0.18
40947 verbose lifecycle kerberos@0.0.18~install: unsafe-perm in lifecycle false
40948 verbose lifecycle kerberos@0.0.18~install: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/vagrant/node_modules/kerberos/node_modules/.bin:/vagrant/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
40949 verbose lifecycle kerberos@0.0.18~install: CWD: /vagrant/node_modules/kerberos
40950 silly lifecycle kerberos@0.0.18~install: Args: [ '-c', '(node-gyp rebuild) || (exit 0)' ]
40951 verbose stack Error: spawn ENOMEM
40951 verbose stack     at exports._errnoException (util.js:856:11)
40951 verbose stack     at ChildProcess.spawn (internal/child_process.js:298:11)
40951 verbose stack     at exports.spawn (child_process.js:362:9)
40951 verbose stack     at spawn (/usr/lib/node_modules/npm/lib/utils/spawn.js:7:13)
40951 verbose stack     at runCmd_ (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:224:14)
40951 verbose stack     at /usr/lib/node_modules/npm/lib/utils/lifecycle.js:186:7
40951 verbose stack     at nextTickCallbackWith0Args (node.js:452:9)
40951 verbose stack     at process._tickCallback (node.js:381:13)
40952 verbose cwd /vagrant
40953 error Linux 3.13.0-74-generic
40954 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
40955 error node v5.4.1
40956 error npm  v3.3.12
40957 error code ENOMEM
40958 error errno ENOMEM
40959 error syscall spawn
40960 error spawn ENOMEM
40961 error If you need help, you may report this error at:
40961 error     <https://github.com/npm/npm/issues>
40962 verbose exit [ 1, true ]
```

Full provisioning file:
```
#!/usr/bin/env bash

echo "Updating existing packages..."
sudo apt-get update -y || exit 1

echo "Installing build-essential..."
sudo apt-get install -y build-essential || exit 1

echo "Installing libssl-dev..."
sudo apt-get install -y libssl-dev || exit 1

echo "Installing libkrb5-dev..."
sudo apt-get install -y libkrb5-dev || exit 1

echo "Installing MongoDB..."
sudo apt-get install -y mongodb || exit 1

echo "Installing NodeJS..."
curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash - || exit 1
sudo apt-get install -y nodejs || exit 1

echo "Entering SuperUser mode..."
sudo su || exit 1

echo "Installing global NodeJS packages..."
npm install forever grunt-cli node-gyp -g || exit 1

echo "Installing local NodeJS packages..."
cd /vagrant || exit 1
    rm -rf node_modules || exit 1
    npm install --unsafe-perm || exit 1
cd - || exit 1

echo "Compiling source files using Grunt..."
cd /vagrant || exit 1
    grunt build || exit 1
cd - || exit 1

echo "Provisioning MongoDB server..."
mkdir -p /data/db || exit 1
sudo chown `id -u` /data/db || exit 1

echo "Starting MongoDB server..."
mongod --quiet --fork --logpath /var/log/mongod.log || exit 1

echo "Starting NodeJS server..."
cd /vagrant || exit 1
    forever start server.js || exit 1
cd - || exit 1
```

**Comment by christkv** [comment]
you are getting an out of memory error from the compiler

**Comment by StephanBijzitter** [comment]
You're right. Apologies for jumping the trigger, upped the memory to 1GB and everything went smooth as can be.
