### ISSUE TITLE
build fails: ../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory

### ISSUE THREAD

**Issue by funkenstrahlen** [christkv/kerberos#45]
```
> kerberos@0.0.19 install /home/stefan/parse-test/parse-server-example/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory '/home/stefan/parse-test/parse-server-example/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
kerberos.target.mk:94: recipe for target 'Release/obj.target/kerberos/lib/kerberos.o' failed
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory '/home/stefan/parse-test/parse-server-example/node_modules/kerberos/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/stefan/parse-test/parse-server-example/node_modules/kerberos
gyp ERR! node -v v4.3.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
```

**Comment by funkenstrahlen** [comment]
Could fix it with `sudo apt-get install libkrb5-dev`

**Comment by gsaslis** [comment]
FWIW the package for CentOS is `krb5-devel`

**Comment by giuliohome** [comment]
What to do for SUSE Linux Enterprise Server 12.5 ?

**Comment by xlucvvs** [comment]
> What to do for SUSE Linux Enterprise Server 12.5 ?

did you discover the package?

**Comment by giuliohome** [comment]
> > What to do for SUSE Linux Enterprise Server 12.5 ?
> 
> did you discover the package?

Yes:

> Install the RPMs.  On a machine designated as the KDC, install the following software packages: krb5, krb5-server and krb5-client packages

From [source](https://documentation.suse.com/sles/12-SP4/html/SLES-all/cha-security-kerberos.html#sec-security-kerberos-admin-instkdc)

HTH but let me know
