### ISSUE TITLE
Error: Cannot find module '../build/Release/kerberos'

### ISSUE THREAD

**Issue by thecodejack** [christkv/kerberos#63]
Getting this error while accessing kerberos. And there is no folder with name `build` inside `lib` folder. What can be the issue? 

Error: Cannot find module '../build/Release/kerberos'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/dev/my_proj/node_modules/kerberos/lib/kerberos.js:1:78)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by v-suhame** [comment]
I ran into the same error for tests running in [travis ](https://travis-ci.org/christkv/kerberos/jobs/265666035#L282). The root cause for failure was `Error: Cannot find module 'minimatch'`, if you have the same cause or something similar, checkout this issue https://github.com/nodejs/node/issues/3922

**Comment by thecodejack** [comment]
For me its more of `postinstall` not running properly. I deleted node_modules/kerberos folder and installed it again to work properly. Please note that just reinstalling didn't solve the issue. You need to delete the kerberos folder as well.
